<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorExcelSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Insert 6 Main Categories
        $categories = [
            ['name' => 'Industrial & Other Products', 'slug' => 'industrial-other-products', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Grains & Oils', 'slug' => 'grains-oils', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dehydrated & Processed Foods', 'slug' => 'dehydrated-processed-foods', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Food & Beverages', 'slug' => 'food-beverages', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Agriculture & Fresh Produce', 'slug' => 'agriculture-fresh-produce', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Snacks & Sweets', 'slug' => 'snacks-sweets', 'created_at' => now(), 'updated_at' => now()]
        ];
        
        DB::table('vendor_categories')->insertOrIgnore($categories);
        
        DB::table('vendor_categories')->insertOrIgnore([
            ['name' => 'Uncategorized', 'slug' => 'uncategorized', 'created_at' => now(), 'updated_at' => now()]
        ]);

        $dbCategories = DB::table('vendor_categories')->get();
        $categoryIds = [];
        foreach($dbCategories as $cat) {
            $categoryIds[$cat->name] = $cat->id;
        }
        $uncategorizedId = $categoryIds['Uncategorized'] ?? 1;

        // 2. Insert Vendors mapped to the Main Category IDs
        $vendors = [
            [
                'company_name' => 'MANA Ceylon Manufactures (Pvt) Ltd.',
                'slug' => 'mana-ceylon-manufactures-pvt-ltd',
                'vendor_category_id' => $categoryIds['Industrial & Other Products'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0714901088',
                'address' => 'Rajanganaya Track No. 13/14',
                'city' => 'Rajanganaya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2011,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Crystal Pearl (Pvt) Ltd.',
                'slug' => 'crystal-pearl-pvt-ltd',
                'vendor_category_id' => $categoryIds['Grains & Oils'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0766544346',
                'address' => 'No.36, Kumbukkanda, Maha Iluppallam',
                'city' => 'Thalawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2019,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'N-Ceylon ',
                'slug' => 'n-ceylon',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0777308365',
                'address' => 'No. 2540, Senanayake Mawatha, Anuradhapura',
                'city' => 'NPE',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2023,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'RM Products',
                'slug' => 'rm-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0765517020',
                'address' => 'Manelwewa, Pahalahalmillawa',
                'city' => 'Nochchiyagama',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2021,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Pramode Rice',
                'slug' => 'pramode-rice',
                'vendor_category_id' => $categoryIds['Grains & Oils'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0712112458',
                'address' => 'No. 94, Jayanthigrama, Saliyapura',
                'city' => 'NPC',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2017,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Tyni Tiyana Enterprises',
                'slug' => 'tyni-tiyana-enterprises',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0770305001',
                'address' => '2nd Lane, Sandagama, Aaththikulama, Nelumkulama',
                'city' => 'NPE',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2020,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Mihiri Food Products ',
                'slug' => 'mihiri-food-products',
                'vendor_category_id' => $categoryIds['Grains & Oils'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0716450356',
                'address' => 'No. 78, Adiyagala Road, Madatugama',
                'city' => 'Kekirawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2018,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Kalara Products',
                'slug' => 'kalara-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0742311862',
                'address' => 'No. 211, Sunda Mawatha, Megodawewa',
                'city' => 'Galenbidunuwewa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2022,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Sasoba Enterprises',
                'slug' => 'sasoba-enterprises',
                'vendor_category_id' => $categoryIds['Industrial & Other Products'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0770609292',
                'address' => 'N0. 201, Padikaramaduwa',
                'city' => 'Galenbidunuwewa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2021,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Ranjith Products',
                'slug' => 'ranjith-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0713912176',
                'address' => 'D5, Ela Road, Mudungoda, Kirogama',
                'city' => 'Thalawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2016,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Parami Dairy (Pvt) Ltd.',
                'slug' => 'parami-dairy-pvt-ltd',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0769121002',
                'address' => 'Katakaale, Kiralogama',
                'city' => 'Thalawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2002,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Rajanganaya A-park Ltd (PUC)',
                'slug' => 'rajanganaya-a-park-ltd-puc',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0771734864',
                'address' => 'Rajanganaya Track No. 4',
                'city' => 'Rajanganaya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2022,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Saratha Product and Services',
                'slug' => 'saratha-product-and-services',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0764165259',
                'address' => 'Nanana Pahana, Anuradhapura Road',
                'city' => 'Mihintalee',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2025,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Lanka Kings Food Products',
                'slug' => 'lanka-kings-food-products',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0711460287',
                'address' => '601/46/1, Samagi Udaya, Airport Road, Anuradhapura',
                'city' => 'NPE',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2013,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Coco Heat Lanka Enterprises (Pathilana)',
                'slug' => 'coco-heat-lanka-enterprises-pathilana',
                'vendor_category_id' => $categoryIds['Industrial & Other Products'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0710133465',
                'address' => 'Waragoda, Kekirawa Road',
                'city' => 'Thalawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2020,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'S&M Agro (Pvt) Ltd. (Sampath)',
                'slug' => 's-m-agro-pvt-ltd-sampath',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0764456000',
                'address' => 'No. 64, South Bank',
                'city' => 'Rajanganaya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2018,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Royal Food Lanka (Pvt) Ltd.',
                'slug' => 'royal-food-lanka-pvt-ltd',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0724230065',
                'address' => 'Rajanganaya Junction',
                'city' => 'Thambuttegama',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2012,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Sameera Sesame Product',
                'slug' => 'sameera-sesame-product',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0761753570',
                'address' => 'No. 15, Sangalikanadarawa',
                'city' => 'Medawachchiya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2013,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Devaki Agro Industries (Pvt) Ltd.',
                'slug' => 'devaki-agro-industries-pvt-ltd',
                'vendor_category_id' => $categoryIds['Grains & Oils'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0777344784',
                'address' => 'No.90, Sekkupitiya',
                'city' => 'Kekirawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => null,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Rain Eco Products (Pvt) Ltd.',
                'slug' => 'rain-eco-products-pvt-ltd',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0774942530',
                'address' => 'Kekirawa Road',
                'city' => 'Thirapane',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2024,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Jayamali Herbal & Grain Products',
                'slug' => 'jayamali-herbal-grain-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0711093485',
                'address' => 'Ganickkulama, Uttimaduwa',
                'city' => 'Thirapane',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2024,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Minchi Bite Products',
                'slug' => 'minchi-bite-products',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0714421128',
                'address' => 'No. 125/3, Chamindu Sewana, Ethumalpitiya',
                'city' => 'Thamankaduwa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2007,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Welagedara Products',
                'slug' => 'welagedara-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0785380185',
                'address' => 'No.15, Magulpokuna',
                'city' => 'Welikanda',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2020,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Lithara Products (Pvt) Ltd. ',
                'slug' => 'lithara-products-pvt-ltd',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0762259124',
                'address' => 'No. 3073/508, Alekembulawa, Diyabeduma',
                'city' => 'Elahera',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2018,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Vonro Milk Products',
                'slug' => 'vonro-milk-products',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0719091432',
                'address' => 'No. 3/7, Circuler Road Wasundara Mawatha, Polonnaruwa New Town',
                'city' => 'Thamankaduwa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2007,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Weerasinha Spice Products',
                'slug' => 'weerasinha-spice-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0760672302',
                'address' => 'No. 480, Biso uyana , Diyasenpura',
                'city' => 'Madirigiriya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2014,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'NKD Products (Nanayakkara)',
                'slug' => 'nkd-products-nanayakkara',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0775466695',
                'address' => 'No. 1120/1, Shanthipura, Unagalawehera',
                'city' => 'Thamankaduwa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2020,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Amasha Sweet House',
                'slug' => 'amasha-sweet-house',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0786981802',
                'address' => 'No. 318, Yaya 12, Nagarapura, Ambagaswewa',
                'city' => 'Madirigiriya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2018,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Rusiru Yoghurt',
                'slug' => 'rusiru-yoghurt',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0777201900',
                'address' => '30/14, Thambalawewa , Jayanthipura',
                'city' => 'Hingutakgoda',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 1992,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Ulankulama Dairies (Pvt) Ltd.',
                'slug' => 'ulankulama-dairies-pvt-ltd',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0255678489',
                'address' => 'Ulankulama, Maradankadawala',
                'city' => 'Kekirawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2017,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Healthy Foods Lanka Exports (Pvt) Ltd.',
                'slug' => 'healthy-foods-lanka-exports-pvt-ltd',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0718109532',
                'address' => 'Maliyadewa Mawatha, Anuradhapura',
                'city' => 'NPE',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2014,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'EV Ceylon Nature Product',
                'slug' => 'ev-ceylon-nature-product',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0775066627',
                'address' => null,
                'city' => 'Thambuththegama',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => null,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Shenu Mushroom Production/
Casky Products',
                'slug' => 'shenu-mushroom-production-casky-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '
\'0769000393',
                'address' => 'Pihibiyagollawa',
                'city' => 'Medawachchiya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2021,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Green Agro Ventures (Pvt) Ltd.',
                'slug' => 'green-agro-ventures-pvt-ltd',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => null,
                'address' => '81, Kubuk Anda, Mahailluppallama',
                'city' => 'Kekirawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2023,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Bimmala Mushroom Product',
                'slug' => 'bimmala-mushroom-product',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0768986253',
                'address' => '1st Mile post, Thalawa Road',
                'city' => 'Kekirawa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2023,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Thennakoon Product',
                'slug' => 'thennakoon-product',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '077134807',
                'address' => 'Kibulpatiyawa, Mahapothana',
                'city' => 'Horopathana',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2024,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Three Star (Dairy)',
                'slug' => 'three-star-dairy',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '077134807',
                'address' => 'Kibulpatiyawa, Mahapothana',
                'city' => 'Galenbidunuwewa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2000,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Walauwa Production',
                'slug' => 'walauwa-production',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0769396828',
                'address' => 'Kudawewa Road',
                'city' => 'Nochchiyagama',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2022,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Andrawewa Agri (PUC)',
                'slug' => 'andrawewa-agri-puc',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => null,
                'address' => 'Andrawewa',
                'city' => 'Nochchiyagama',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2020,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'MRF Enterprise',
                'slug' => 'mrf-enterprise',
                'vendor_category_id' => $categoryIds['Industrial & Other Products'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0779620605',
                'address' => 'Kolibandawewa, Parasangaswewa',
                'city' => 'Rambewa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2004,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Hela Rasa (Pvt) Ltd.',
                'slug' => 'hela-rasa-pvt-ltd',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => null,
                'address' => 'Amane, Srawasthipura',
                'city' => 'NPC',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2021,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Rajanganaya Export ',
                'slug' => 'rajanganaya-export',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => null,
                'address' => 'Rajanganaya Track No. 5',
                'city' => 'Rajanganaya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2023,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'DNM Mushroom',
                'slug' => 'dnm-mushroom',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0779186712',
                'address' => 'LB9, Kaudulla',
                'city' => 'Madirigiriya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2023,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Pulathisi Supipi Mushroom',
                'slug' => 'pulathisi-supipi-mushroom',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0773343587',
                'address' => 'No. 253/3, 4 Ela, Polonnaruwa',
                'city' => 'Thamankaduwa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2008,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'New Nirosha Dairy Products',
                'slug' => 'new-nirosha-dairy-products',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0777742922',
                'address' => '52, Shanthi lane, Kaduruweala, Thamankaduwa',
                'city' => 'Thamankaduwa',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2024,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'RSI Dry Products',
                'slug' => 'rsi-dry-products',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0777481157',
                'address' => '890/3, Unagalawehera',
                'city' => 'Hingutakgoda',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2021,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'N&L Mushroom Products',
                'slug' => 'n-l-mushroom-products',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0713510118',
                'address' => '68, Akkara 45, Thalpotha',
                'city' => 'Lankapura',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2024,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Leo Foods (Pvt) Ltd.',
                'slug' => 'leo-foods-pvt-ltd',
                'vendor_category_id' => $categoryIds['Dehydrated & Processed Foods'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0714223919 ',
                'address' => 'Kottepitiya',
                'city' => 'Elahera',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2023,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'KPG Mushroom Products',
                'slug' => 'kpg-mushroom-products',
                'vendor_category_id' => $categoryIds['Agriculture & Fresh Produce'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0719160453',
                'address' => 'Gangeyaya',
                'city' => 'Elahera',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2021,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Sha Food Products (Pvt) Ltd.',
                'slug' => 'sha-food-products-pvt-ltd',
                'vendor_category_id' => $categoryIds['Food & Beverages'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0788756998',
                'address' => 'No. 36, Samapura, New Town',
                'city' => 'Madirigiriya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => 2010,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Kumari Tea Marketing',
                'slug' => 'kumari-tea-marketing',
                'vendor_category_id' => $categoryIds['Snacks & Sweets'] ?? $uncategorizedId,
                'description' => null,
                'logo' => null,
                'banner' => null,
                'website' => null,
                'email' => null,
                'phone' => '0774129154',
                'address' => null,
                'city' => 'Madirigiriya',
                'state' => 'North Central',
                'country' => 'Sri Lanka',
                'postal_code' => null,
                'established_year' => null,
                'employees_count' => null,
                'certifications' => null,
                'status' => 'approved',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('vendors')->insert($vendors);
    }
}
